In [1]:
import pandas as pd
import numpy as np

data = pd.read_csv('Indigenous.csv')
data.head()

,Con,Contp,PP,PPName,Reg,AgtId,Agt,Dat,Status,Lgt,...,TjRep,TjRSym,TjRMa,TjNR,ImUN,ImOth,ImRef,ImPK,ImE,ImSrc
0,Bangladesh/Chittagong Hill Tracts,Government/territory,11,Bangladesh-Chittagong Hills Tracts: peace process,Asia and Pacific,238,Agreement between the National Committee on Ch...,1997-12-02,Multiparty signed/agreed,14,...,2,0,1,0,0,0,0,0,1,1
1,Central African Republic,Inter-group,155,CAR: Local Processes,Africa (excl MENA),2211,P'Comite de Suivi de la Accord de Paix et de R...,2018-11-29,Multiparty signed/agreed,2,...,0,0,0,0,0,0,0,1,1,1
2,Central African Republic,Government,14,CAR: coups and rebellions process,Africa (excl MENA),1442,"Pacte Républicain pour la paix, la réconciliat...",2015-05-11,Multiparty signed/agreed,8,...,1,1,1,2,0,0,0,0,1,1
3,Colombia,Government,101,Colombia V - Santos,Americas,1845,Final Agreement to End the Armed Conflict and ...,2016-11-24,Multiparty signed/agreed,323,...,3,1,1,3,0,0,1,1,1,1
4,Colombia,Government,101,Colombia V - Santos,Americas,1796,Agreement on security guarantees and the fight...,2016-06-23,Multiparty signed/agreed,18,...,0,0,0,2,0,1,0,1,0,1

In [4]:
data["Year"]=[data["Dat"][i][0:4] for i in range(len(data["Dat"]))]
data['Con']=[data["Con"][i].replace('(','').replace(')','') for i in range(len(data["Con"]))]

In [5]:
import re
names=pd.read_excel('Country_names.xlsx')
names.head()

country=[]
code=[]
Con_Times=[]
AgtId=[]
Year=[]
Reg=[]

def find_equals(c):
    l = len(c)
    for i in range(l-1):
        if c[i] != c[i+1]:
                return False
    return True



for j in range(len(names["country"])):
    nombres=[re.search(names["country"][j], data["Con"][i]) for i in range(len(data["Con"]))]
    if find_equals(nombres)==False:
        for k in range(len(nombres)):
            if nombres[k]!=None: 
                country.append(names["country"][j]) 
                code.append(names["code"][j]) 
                Con_Times.append(data["Con"][k])                                                        
                AgtId.append(data["AgtId"][k])  
                Year.append(data["Year"][k])
                Reg.append(data["Reg"][k])
                

correct_names = {"Country": country , "Loc1ISO": code , "Con_Times": Con_Times, "AgtId": AgtId, "Year": Year,"Region": Reg}

CN=pd.DataFrame(correct_names)
CN

,Country,Loc1ISO,Con_Times,AgtId,Year,Region
0,Bangladesh,BGD,Bangladesh/Chittagong Hill Tracts,238,1997,Asia and Pacific
1,Central African Republic,CAF,Central African Republic,2211,2018,Africa (excl MENA)
2,Central African Republic,CAF,Central African Republic,1442,2015,Africa (excl MENA)
3,Colombia,COL,Colombia,1845,2016,Americas
4,Colombia,COL,Colombia,1796,2016,Americas
...,...,...,...,...,...,...
126,Sudan,SDN,South Sudan/Sudan,498,2004,Africa (excl MENA)
127,Sudan,SDN,South Sudan/Sudan/Southern Kordofan - Blue Nil...,1033,1996,Africa (excl MENA)
128,Uganda,UGA,Uganda,888,2007,Africa (excl MENA)
129,Zimbabwe,ZWE,Zimbabwe,1340,2013,Africa (excl MENA)
130,Zimbabwe,ZWE,Zimbabwe,826,2008,Africa (excl MENA)

In [7]:
len(data["Con"].unique())

26

In [8]:
len(CN['Con_Times'].unique())

26

In [9]:
d=data["Con"].unique()
cn=CN['Con_Times'].unique()

for j in range(len(d)):
    v=[re.search(d[j], cn[i]) for i in range(len(cn))]
    if find_equals(v)==True:
        print(d[j])

In [12]:
CN.to_excel('Indigenous_country.xlsx')